Add cross domain iframe startegy
KanoComputing/kano-world-js-sdk pull request #18
Opened 2016-09-12 14:34 UTC by paulvarache

Related to https://trello.com/c/WfiZjOUQ/264-3-unified-login

2016-09-15 16:57 UTC, rcocetta commented
You need to bump the package.json to release this

2016-09-15 17:28 UTC, andreiconstantinescu commented
can't we implement a more elegant method? like sso?

2016-09-15 17:35 UTC, arifshanji requested changes

2016-09-15 17:35 UTC, arifshanji commented on xdAuthIframe.html
> +                    /^http(s)?:\/\/(.*)(\.)?kano.me$/,
We have kano.zendesk.com hitting our API.  It should be in this list.

2016-09-15 17:36 UTC, paulvarache commented on xdAuthIframe.html
> +                    /^http(s)?:\/\/(.*)(\.)?kano.me$/,
This origin refer to the frontend apps calling the iframe. Something calling the API won't be affected

2016-09-15 17:51 UTC, paulvarache commented
I'd be happy to do so. If you know a solution to share localStorage data between domains, please send me more info about it and we'll re-architecture the thing

2016-09-16 09:43 UTC, arifshanji approved these changes

2016-09-16 09:43 UTC, merged

2016-09-16 14:08 UTC, andreiconstantinescu commented
we could've used a strategy of sso of passing a query string, verifying it and singing in the user  accordingly (writing to localstorage/cookie) and avoinding hidden iframes ... anyway, is redundant now.